In [ ]:
import cv2 as cv
import numpy as np
import glob
from matplotlib import pyplot as plt
list1=glob.glob('/content/drive/MyDrive/datatstes/fresh_banana/*.png')
list2=glob.glob('/content/drive/MyDrive/datatstes/rotten_banana/*.png')

In [ ]:
def labeling(name_list,label, X, y):
    for i in name_list:
        y.append(label)
        img=cv.imread(i,0) 
        img=cv.resize(img, (50, 50))
        X.append(img.ravel())

X=[]
y=[]
labeling(list1,1,X,y)
labeling(list2,0,X,y)
X = np.vstack(X).astype(None)
y = np.array([y]).T

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_max = X_train.max()
X_min = X_train.min()
X_train_scaled = np.array([(x - X_min) / (X_max - X_min) for x in X_train])
X_test_scaled = np.array([(x - X_min) / (X_max - X_min) for x in X_test])

In [ ]:
def computeDistance(item, img):
  result = 0
  for i in range(len(item)):
    result += (item[i] - img[i])**2
  return np.sqrt(result)

In [ ]:
def computeKNN(imgs_train, labels_train, item, k):
  distance = []
  for img, label in zip(imgs_train, labels_train):
    distance.append(
        {
            "label": label,
            "value": computeDistance(item, img)
        }
    )
  distance.sort(key= lambda x:x["value"])
  label = [item['label'] for item in distance]
  return label[:k]


In [ ]:
def calculate_mode(arr: np.ndarray):
    (values, counts) = np.unique(arr, return_counts=True)
    index = np.argmax(counts)
    return values[index]

In [ ]:
def voteTheDistance(imgs_train, labels_train, item, k):
  knn = np.asarray(computeKNN(imgs_train, labels_train, item, k))
  label = calculate_mode(knn)
  return label

In [ ]:
y_pred = []
for i in X_test:
  y_pred.append(voteTheDistance(X_train, y_train, i, 5))

[0. 0. 0. ... 0. 0. 0.]
[255. 255. 255. ... 255. 255. 255.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


KeyboardInterrupt: ignored